### ISSUE TITLE
全是报错

### ISSUE THREAD

**Issue by Gx952743985** [caixindong/Running-Life---iOS#2]

**Comment by caixindong** [comment]
哪里报错

**Comment by Gx952743985** [comment]
我下载下来报错46个,我该怎么给你看到呢

**Comment by caixindong** [comment]
你可以截图给我看下吗

**Comment by Gx952743985** [comment]
我不知道这个怎么给你看截图

**Comment by Gx952743985** [comment]
![a6347deb-2960-4b07-96f1-f9dad77f10aa](https://cloud.githubusercontent.com/assets/16395032/18430383/e23f3eca-790a-11e6-9bef-f5be99f7daef.png)

**Comment by caixindong** [comment]
这个好像不是我的项目。。。。我的项目叫Cool Run

**Comment by caixindong** [comment]
看到了

**Comment by caixindong** [comment]
你重新pod install 下

**Comment by caixindong** [comment]
![image](https://cloud.githubusercontent.com/assets/11926151/18430480/45f2aa42-790b-11e6-9471-23c06c898bb7.png)
这里改一下

**Comment by caixindong** [comment]
你看是不是YES

**Comment by Gx952743985** [comment]
是的,是YES
